# Presentation category/categories - Required
categories: [ category ]
# Presentation title
title: Title of your beautiful presentation
# Subtitle - Not mandatory
subtitle: Subtitle here
# Cover - Required
cover: cover-intro.jpg
# Author - Required
author:
  name: Author Name
  role: Author Role
  picture: author-picture.jpg
  description: >
    <p>
      Author description.
    </p>
# Presentation description - not mandatory
description: >
  <p>
    Introduction to your presentation here.
  </p>
# Language
lang: en_EN
# Meta tags
meta:
  # Title - required
  title: Title of your beautiful presentation
  description: Description here
  # Replace with your tags
  keywords:
    - Confetti
    - Presentation
    - Slide deck
    - CMS
theme: voice
